site_name: My Docs

site_url: https://mydomain.org/mysite
theme:
  name: material
  palette: 
    scheme: default
    primary: teal
    accent: brown
  features:
    - navigation.path
    - navigation.top
  

plugins:
  - offline
  - search
      

